### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by AnderRasoVazquez** [mirkobrombin/ElementaryPython#3]
It would be nice to have some folders with the structure of a multilingual application.

+ [Python3 gettext module docs](https://docs.python.org/3/library/gettext.html).

**Comment by mirkobrombin** [comment]
Good idea! I add it to the list.

**Comment by mirkobrombin** [comment]
Created a multilingual example [here](https://github.com/mirkobrombin/Bottles).
I'll integrate it soon into the template.

**Comment by mirkobrombin** [comment]
Integrated c575b4b
